server:
  port: 8080

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://prd-starcoin.cluster-ct4tlgfmee0j.ap-southeast-1.rds.amazonaws.com/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: Z1P8q4moD9NjAZxC9CDc

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: prd-starcoin-redis.xplek9.0001.apse1.cache.amazonaws.com
    port: 6379
    password:

## ------------------------------业务相关配置写到下面-------------------------

ido:
  star:
    dx:
      resourceUrl: https://main-seed.starcoin.org
      moduleName: 0x89e1db66b5879bf19f5c1cc7d12d901a::Offering
    swap:
      websocket-host: 60.205.3.84
      websocket-port: 8970
      websocket-contract-address: 64c66296d98d6ab08579b14487157e05
