server:
  port: 8991

# database HikariCP相关配置
spring:
  datasource:
#    url: jdbc:mysql://101.201.46.114:3306/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: crypto_rw
#    password: crypto_rw_password
    url: jdbc:mysql://52.77.131.111:3306/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: OdeWzZNalcTPk2LAo0Lg

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: 101.201.46.114
    port: 6379
    password: 123456


## 日志配置
logging:
  path: logs
  logLevel: INFO


## ------------------------------业务相关配置写到下面-------------------------

ido:
  star:
    dx:
      resourceUrl: https://main-seed.starcoin.org
      moduleName: 0x64c66296d98d6ab08579b14487157e05::Offering
    swap:
      websocket-host: 13.229.71.62
      websocket-port: 9870
      websocket-contract-address: 64c66296d98d6ab08579b14487157e05
      contract-address: c9cf2dd64e30c9b587c4f818adcc0eef
      lp-pool-resource-name: 0xc9cf2dd64e30c9b587c4f818adcc0eef::SwapPair::SwapPair
      usdt-address: 0x5b876a58b0e1cff855b6489cd8cf3bec::DummyToken::USDT
    runner:
      swap-consumer:
        core-threads: 1
        max-threads: 1
    client:
      url: https://main-seed.starcoin.org
      chain-id: 1
    nft:
      websocket-host: 13.229.71.62
      websocket-port: 9870
      market: "0xa85291039ddad8845d5097624c81c3fd"
      scripts: "0x290c7b35320a4dd26f651fd184373fe7"
      catadd: "0x69f1e543a3bef043b63bed825fcd2cf6"
      market-module: "NFTMarket05"
      scripts-module: "NFTScripts05"
      image-prefix: "https://imagedelivery.net"
      image-base-path: "/Users/bixin/Documents/pics/nft/"
      image-info-api: "https://test.kikoswap.com/v1/nft/image/info/"
      image-group-api: "https://test.kikoswap.com/v1/nft/image/group/"
    mining:
      nft-mining-day-reward: 10
      nft-mining-block-reward: 10
      nft-unit-price: 10
      nft-mining-address: "0xa85291039ddad8845d5097624c81c3fd"
      nft-mining-module: "NFTMining"
      nft-mining-stc-fee: 0.01
