server:
  port: 8080

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://sandbox-starcoin.cluster-ct4tlgfmee0j.ap-southeast-1.rds.amazonaws.com/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: OdeWzZNalcTPk2LAo0Lg

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: sandbox-starcoin-redis.xplek9.ng.0001.apse1.cache.amazonaws.com
    port: 6379
    password:

## 日志配置
logging:
  # 日志级别
  logLevel: INFO
  # 日志保留天数，默认10天
  maxHistory: 5
## ------------------------------业务相关配置写到下面-------------------------

ido:
  star:
    dx:
      resourceUrl: https://main-seed.starcoin.org
      moduleName: 0x64c66296d98d6ab08579b14487157e05::Offering
    swap:
      websocket-host: 10.13.22.40
      websocket-port: 9870
      websocket-contract-address: c9097c917625f3b01d59b375e0630b07
      contract-address: c9097c917625f3b01d59b375e0630b07
      lp-pool-resource-name: 0xc9097c917625f3b01d59b375e0630b07::SwapPair::SwapPair
      lp-token-resource-name: 0xc9097c917625f3b01d59b375e0630b07::SwapPair::LPToken
      usdt-address: 0x5b876a58b0e1cff855b6489cd8cf3bec::DummyToken::USDT
    runner:
      swap-consumer:
        core-threads: 1
        max-threads: 1
    client:
      url: https://main-seed.starcoin.org
      chain-id: 1
    nft:
      websocket-host: 10.13.22.40
      websocket-port: 9870
      market: "0xa85291039ddad8845d5097624c81c3fd"
      scripts: "0x290c7b35320a4dd26f651fd184373fe7"
      catadd: "0x69f1e543a3bef043b63bed825fcd2cf6"
      market-module: "NFTMarket05"
      scripts-module: "NFTScripts05"
      image-prefix: "https://imagedelivery.net"
      image-base-path: "/data/images/bixin-ido-server/nft/"
      image-info-api: "https://test.kikoswap.com/v1/nft/image/info/"
      image-group-api: "https://test.kikoswap.com/v1/nft/image/group/"

