server:
  port: 8991

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://101.201.46.114:3306/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: crypto_rw
    password: crypto_rw_password

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: 101.201.46.114
    port: 6379
    password: 123456

## ------------------------------业务相关配置写到下面-------------------------

ido:
  dx:
    star:
      resourceUrl: https://barnard-seed.starcoin.org
      moduleName: 0x64c66296d98d6ab08579b14487157e05::Offering
