server:
  port: 8080

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://sandbox-starcoin.cluster-ct4tlgfmee0j.ap-southeast-1.rds.amazonaws.com/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: OdeWzZNalcTPk2LAo0Lg

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: sandbox-starcoin-redis.xplek9.ng.0001.apse1.cache.amazonaws.com
    port: 6379
    password:
## ------------------------------业务相关配置写到下面-------------------------

ido:
  star:
    dx:
      resourceUrl: https://main-seed.starcoin.org
      moduleName: 0x64c66296d98d6ab08579b14487157e05::Offering
    swap:
      websocket-host: 10.13.22.40
      websocket-port: 9870
      websocket-contract-address: c9097c917625f3b01d59b375e0630b07
      contract-address: c9097c917625f3b01d59b375e0630b07
      lp-pool-resource-name: 0xc9097c917625f3b01d59b375e0630b07::SwapPair::SwapPair
    runner:
      swap-consumer:
        core-threads: 1
        max-threads: 1
    client:
      url: https://main-seed.starcoin.org
      chain-id: 251
    nft:
      websocket-host: 10.13.22.40
      websocket-port: 9870
      market: "0x290c7b35320a4dd26f651fd184373fe7"
      catadd: "0xd30b4de81d71c1793aa4db4763211e63"
      scripts: "0x290c7b35320a4dd26f651fd184373fe7"
