server:
  port: 8080

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://sandbox-starcoin.cluster-ct4tlgfmee0j.ap-southeast-1.rds.amazonaws.com/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: OdeWzZNalcTPk2LAo0Lg

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: sandbox-starcoin-redis.xplek9.ng.0001.apse1.cache.amazonaws.com
    port: 6379
    password:
## ------------------------------业务相关配置写到下面-------------------------

ido:
  star:
    dx:
      resourceUrl: https://main-seed.starcoin.org
      moduleName: 0x64c66296d98d6ab08579b14487157e05::Offering
    swap:
      websocket-host: 10.13.22.40
      websocket-port: 9870
      websocket-contract-address: 3cf910d97c98947277be21d6b7625cfe
      contract-address: 3cf910d97c98947277be21d6b7625cfe
      lp-pool-resource-name: 0x3cf910d97c98947277be21d6b7625cfe::SwapPair::SwapPair
    runner:
      swap-consumer:
        core-threads: 1
        max-threads: 1