server:
  port: 8991

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://101.201.46.114:3306/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: crypto_rw
    password: crypto_rw_password

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: 101.201.46.114
    port: 6379
    password: 123456


## 日志配置
logging:
  path: logs
  logLevel: INFO


## ------------------------------业务相关配置写到下面-------------------------

ido:
  star:
    dx:
      resourceUrl: https://barnard-seed.starcoin.org
      moduleName: 0x64c66296d98d6ab08579b14487157e05::Offering
    swap:
      websocket-host: 60.205.3.84
      websocket-port: 8970
      websocket-contract-address: 64c66296d98d6ab08579b14487157e05
      contract-address: c9cf2dd64e30c9b587c4f818adcc0eef
      lp-pool-resource-name: 0xc9cf2dd64e30c9b587c4f818adcc0eef::SwapPair::SwapPair
    runner:
      swap-consumer:
        core-threads: 1
        max-threads: 1
    client:
      url: https://main-seed.starcoin.org
      chain-id: 1
    nft:
      websocket-host: 60.205.3.84
      websocket-port: 8970
      market: "0xA85291039DdAD8845D5097624C81C3Fd"
      scripts: "0xA85291039DdAD8845D5097624C81C3Fd"
      catadd: "0x69F1E543A3BeF043B63BEd825fcd2cf6"
      market-module: "NFTMarket"
      scripts-module: "NFTScripts"
      image-prefix: "https://imagedelivery.net"
      image-base-path: "/Users/bixin/Documents/pics/nft/"
