server:
  port: 8991

# database HikariCP相关配置
spring:
  datasource:
#    url: jdbc:mysql://101.201.46.114:3306/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: crypto_rw
#    password: crypto_rw_password
#    url: jdbc:mysql://52.77.131.111:3306/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: admin
#    password: OdeWzZNalcTPk2LAo0Lg
#    url: jdbc:mysql://localhost:3306/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password:
    url: jdbc:mysql://13.213.126.178:3306/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: Z1P8q4moD9NjAZxC9CDc

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
#    host: 101.201.46.114
#    port: 6379
#    password: 123456
    host: localhost
    port: 6379
    password:


## 日志配置
logging:
  path: logs
  logLevel: DUBUG


## ------------------------------业务相关配置写到下面-------------------------

ido:
  star:
    dx:
      resourceUrl: https://main-seed.starcoin.org
      moduleName: 0x89e1db66b5879bf19f5c1cc7d12d901a::Offering
    swap:
      websocket-host: 10.103.63.231
      websocket-port: 9870
      websocket-contract-address: a371dcd3556f40221b480bd1792c02ad
      contract-address: a371dcd3556f40221b480bd1792c02ad
      lp-pool-resource-name: 0xa371dcd3556f40221b480bd1792c02ad::SwapPair::SwapPair
      lp-token-resource-name: 0xa371dcd3556f40221b480bd1792c02ad::SwapPair::LPToken
      usdt-address: 0x9350502a3af6c617e9a42fa9e306a385::BX_USDT::BX_USDT
    runner:
      swap-consumer:
        core-threads: 1
        max-threads: 1
    client:
      url: https://main-seed.starcoin.org
      chain-id: 1
    nft:
      websocket-host: 10.103.63.231
      websocket-port: 9870
      market: "0x7ed4261b68ddb20158109794bbab3ae7"
      scripts: "0x7ed4261b68ddb20158109794bbab3ae7"
      catadd: "0x8355417c88d969f656935244641256ad"
      market-module: "NFTMarket"
      scripts-module: "NFTScripts"
      image-prefix: "https://imagedelivery.net"
      image-base-path: "/data/images/bixin-ido-server/nft/"
      image-info-api: "https://kikoswap.com/v1/nft/image/info/"
      image-group-api: "https://kikoswap.com/v1/nft/image/group/"
      composite-fee: 0.01
      composite-url: "http://10.13.43.146:8080/create_nft/"
    mining:
      nft-mining-day-reward: 2765.0000016
      nft-mining-block-reward: 0.192013889
      nft-unit-price: 99
      nft-mining-address: "0x7ed4261b68ddb20158109794bbab3ae7"
      nft-mining-module: "NFTMining"
      nft-mining-stc-fee: 0.01

