server:
  port: 8080

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://prd-starcoin.cluster-ct4tlgfmee0j.ap-southeast-1.rds.amazonaws.com/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: Z1P8q4moD9NjAZxC9CDc

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: prd-starcoin-redis.xplek9.0001.apse1.cache.amazonaws.com
    port: 6379
    password:

## 日志配置
logging:
  # 日志级别
  logLevel: INFO
  # 日志保留天数，默认10天
  maxHistory: 5
## ------------------------------业务相关配置写到下面-------------------------

ido:
  star:
    dx:
      resourceUrl: https://main-seed.starcoin.org
      moduleName: 0x89e1db66b5879bf19f5c1cc7d12d901a::Offering
    swap:
      websocket-host: 10.103.63.231
      websocket-port: 9870
      websocket-contract-address: a371dcd3556f40221b480bd1792c02ad
      contract-address: a371dcd3556f40221b480bd1792c02ad
      lp-pool-resource-name: 0xa371dcd3556f40221b480bd1792c02ad::SwapPair::SwapPair
      lp-token-resource-name: 0xa371dcd3556f40221b480bd1792c02ad::SwapPair::LPToken
      usdt-address: 0x9350502a3af6c617e9a42fa9e306a385::BX_USDT::BX_USDT
    runner:
      swap-consumer:
        core-threads: 1
        max-threads: 1
    client:
      url: https://main-seed.starcoin.org
      chain-id: 1
    nft:
      websocket-host: 10.103.63.231
      websocket-port: 9870
      market: "0x7ed4261b68ddb20158109794bbab3ae7"
      scripts: "0x7ed4261b68ddb20158109794bbab3ae7"
      catadd: "0x8355417c88d969f656935244641256ad"
      market-module: "NFTMarket"
      scripts-module: "NFTScripts"
      image-prefix: "https://imagedelivery.net"
      image-base-path: "/data/images/bixin-ido-server/nft/"
      image-info-api: "https://kikoswap.com/v1/nft/image/info/"
      image-group-api: "https://kikoswap.com/v1/nft/image/group/"
