server:
  port: 8080

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://prd-uni-exchange-db.cluster-csc16ll61cuz.ap-southeast-1.rds.amazonaws.com/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: crypto_rw
    password: 9;f4XdP%2sierm67mDcL

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: prd-uni-exchange-redis.qxdcpf.ng.0001.apse1.cache.amazonaws.com
    port: 6379
    password:

## ------------------------------业务相关配置写到下面-------------------------

