server:
  port: 8991

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://101.201.46.114:3306/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: crypto_rw
    password: crypto_rw_password

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: 101.201.46.114
    port: 6379
    password: 123456

## ------------------------------业务相关配置写到下面-------------------------

ido:
  star:
    dx:
      resourceUrl: https://barnard-seed.starcoin.org
      moduleName: 0x64c66296d98d6ab08579b14487157e05::Offering
    swap:
      websocket-host: 60.205.3.84
      websocket-port: 8970
      websocket-contract-address: 64c66296d98d6ab08579b14487157e05
      contract-address: c9cf2dd64e30c9b587c4f818adcc0eef
      lp-pool-resource-name: 0xc9cf2dd64e30c9b587c4f818adcc0eef::SwapPair::SwapPair
    runner:
      swap-consumer:
        core-threads: 1
        max-threads: 1
    client:
      url: https://main-seed.starcoin.org
      chain-id: 251
    nft:
      market: "0x290c7b35320a4dd26f651fd184373fe7"
      scripts: "0x290c7b35320a4dd26f651fd184373fe7"